/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_ik_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[81] = {12, 6, 0, 12, 24, 36, 48, 60, 72, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};

/* robot_ik_expl_vde_forw:(i0[12],i1[12x12],i2[12x6],i3[6],i4[0])->(o0[12],o1[12x12],o2[12x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=1.0000000000000001e-01;
  a2=arg[0]? arg[0][0] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a2=arg[0]? arg[0][1] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[3]? arg[3][3] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[3]? arg[3][4] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[3]? arg[3][5] : 0;
  a2=arg[0]? arg[0][5] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][0]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][1]=a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[1]!=0) res[1][2]=a0;
  a0=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][3]=a0;
  a0=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][4]=a0;
  a0=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][5]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][6]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][7]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][8]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][9]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][10]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][11]=a0;
  a0=arg[1]? arg[1][18] : 0;
  if (res[1]!=0) res[1][12]=a0;
  a0=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][13]=a0;
  a0=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][14]=a0;
  a0=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][15]=a0;
  a0=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][16]=a0;
  a0=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][17]=a0;
  a0=arg[1]? arg[1][12] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][18]=a0;
  a0=arg[1]? arg[1][13] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][19]=a0;
  a0=arg[1]? arg[1][14] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][20]=a0;
  a0=arg[1]? arg[1][15] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][21]=a0;
  a0=arg[1]? arg[1][16] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][22]=a0;
  a0=arg[1]? arg[1][17] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][23]=a0;
  a0=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][24]=a0;
  a0=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][25]=a0;
  a0=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][26]=a0;
  a0=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][27]=a0;
  a0=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][28]=a0;
  a0=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][29]=a0;
  a0=arg[1]? arg[1][24] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][30]=a0;
  a0=arg[1]? arg[1][25] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][31]=a0;
  a0=arg[1]? arg[1][26] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][32]=a0;
  a0=arg[1]? arg[1][27] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][33]=a0;
  a0=arg[1]? arg[1][28] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][34]=a0;
  a0=arg[1]? arg[1][29] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][35]=a0;
  a0=arg[1]? arg[1][42] : 0;
  if (res[1]!=0) res[1][36]=a0;
  a0=arg[1]? arg[1][43] : 0;
  if (res[1]!=0) res[1][37]=a0;
  a0=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][38]=a0;
  a0=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][39]=a0;
  a0=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][40]=a0;
  a0=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][41]=a0;
  a0=arg[1]? arg[1][36] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][42]=a0;
  a0=arg[1]? arg[1][37] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][43]=a0;
  a0=arg[1]? arg[1][38] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][44]=a0;
  a0=arg[1]? arg[1][39] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][45]=a0;
  a0=arg[1]? arg[1][40] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][46]=a0;
  a0=arg[1]? arg[1][41] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][47]=a0;
  a0=arg[1]? arg[1][54] : 0;
  if (res[1]!=0) res[1][48]=a0;
  a0=arg[1]? arg[1][55] : 0;
  if (res[1]!=0) res[1][49]=a0;
  a0=arg[1]? arg[1][56] : 0;
  if (res[1]!=0) res[1][50]=a0;
  a0=arg[1]? arg[1][57] : 0;
  if (res[1]!=0) res[1][51]=a0;
  a0=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][52]=a0;
  a0=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][53]=a0;
  a0=arg[1]? arg[1][48] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][54]=a0;
  a0=arg[1]? arg[1][49] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][55]=a0;
  a0=arg[1]? arg[1][50] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][56]=a0;
  a0=arg[1]? arg[1][51] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][57]=a0;
  a0=arg[1]? arg[1][52] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][58]=a0;
  a0=arg[1]? arg[1][53] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][59]=a0;
  a0=arg[1]? arg[1][66] : 0;
  if (res[1]!=0) res[1][60]=a0;
  a0=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][61]=a0;
  a0=arg[1]? arg[1][68] : 0;
  if (res[1]!=0) res[1][62]=a0;
  a0=arg[1]? arg[1][69] : 0;
  if (res[1]!=0) res[1][63]=a0;
  a0=arg[1]? arg[1][70] : 0;
  if (res[1]!=0) res[1][64]=a0;
  a0=arg[1]? arg[1][71] : 0;
  if (res[1]!=0) res[1][65]=a0;
  a0=arg[1]? arg[1][60] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][66]=a0;
  a0=arg[1]? arg[1][61] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][67]=a0;
  a0=arg[1]? arg[1][62] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][68]=a0;
  a0=arg[1]? arg[1][63] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][69]=a0;
  a0=arg[1]? arg[1][64] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][70]=a0;
  a0=arg[1]? arg[1][65] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][71]=a0;
  a0=arg[1]? arg[1][78] : 0;
  if (res[1]!=0) res[1][72]=a0;
  a0=arg[1]? arg[1][79] : 0;
  if (res[1]!=0) res[1][73]=a0;
  a0=arg[1]? arg[1][80] : 0;
  if (res[1]!=0) res[1][74]=a0;
  a0=arg[1]? arg[1][81] : 0;
  if (res[1]!=0) res[1][75]=a0;
  a0=arg[1]? arg[1][82] : 0;
  if (res[1]!=0) res[1][76]=a0;
  a0=arg[1]? arg[1][83] : 0;
  if (res[1]!=0) res[1][77]=a0;
  a0=arg[1]? arg[1][72] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][78]=a0;
  a0=arg[1]? arg[1][73] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][79]=a0;
  a0=arg[1]? arg[1][74] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][80]=a0;
  a0=arg[1]? arg[1][75] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][81]=a0;
  a0=arg[1]? arg[1][76] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][82]=a0;
  a0=arg[1]? arg[1][77] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][83]=a0;
  a0=arg[1]? arg[1][90] : 0;
  if (res[1]!=0) res[1][84]=a0;
  a0=arg[1]? arg[1][91] : 0;
  if (res[1]!=0) res[1][85]=a0;
  a0=arg[1]? arg[1][92] : 0;
  if (res[1]!=0) res[1][86]=a0;
  a0=arg[1]? arg[1][93] : 0;
  if (res[1]!=0) res[1][87]=a0;
  a0=arg[1]? arg[1][94] : 0;
  if (res[1]!=0) res[1][88]=a0;
  a0=arg[1]? arg[1][95] : 0;
  if (res[1]!=0) res[1][89]=a0;
  a0=arg[1]? arg[1][84] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][90]=a0;
  a0=arg[1]? arg[1][85] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][91]=a0;
  a0=arg[1]? arg[1][86] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][92]=a0;
  a0=arg[1]? arg[1][87] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][93]=a0;
  a0=arg[1]? arg[1][88] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][94]=a0;
  a0=arg[1]? arg[1][89] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][95]=a0;
  a0=arg[1]? arg[1][102] : 0;
  if (res[1]!=0) res[1][96]=a0;
  a0=arg[1]? arg[1][103] : 0;
  if (res[1]!=0) res[1][97]=a0;
  a0=arg[1]? arg[1][104] : 0;
  if (res[1]!=0) res[1][98]=a0;
  a0=arg[1]? arg[1][105] : 0;
  if (res[1]!=0) res[1][99]=a0;
  a0=arg[1]? arg[1][106] : 0;
  if (res[1]!=0) res[1][100]=a0;
  a0=arg[1]? arg[1][107] : 0;
  if (res[1]!=0) res[1][101]=a0;
  a0=arg[1]? arg[1][96] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][102]=a0;
  a0=arg[1]? arg[1][97] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][103]=a0;
  a0=arg[1]? arg[1][98] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][104]=a0;
  a0=arg[1]? arg[1][99] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][105]=a0;
  a0=arg[1]? arg[1][100] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][106]=a0;
  a0=arg[1]? arg[1][101] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][107]=a0;
  a0=arg[1]? arg[1][114] : 0;
  if (res[1]!=0) res[1][108]=a0;
  a0=arg[1]? arg[1][115] : 0;
  if (res[1]!=0) res[1][109]=a0;
  a0=arg[1]? arg[1][116] : 0;
  if (res[1]!=0) res[1][110]=a0;
  a0=arg[1]? arg[1][117] : 0;
  if (res[1]!=0) res[1][111]=a0;
  a0=arg[1]? arg[1][118] : 0;
  if (res[1]!=0) res[1][112]=a0;
  a0=arg[1]? arg[1][119] : 0;
  if (res[1]!=0) res[1][113]=a0;
  a0=arg[1]? arg[1][108] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][114]=a0;
  a0=arg[1]? arg[1][109] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][115]=a0;
  a0=arg[1]? arg[1][110] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][116]=a0;
  a0=arg[1]? arg[1][111] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][117]=a0;
  a0=arg[1]? arg[1][112] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][118]=a0;
  a0=arg[1]? arg[1][113] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][119]=a0;
  a0=arg[1]? arg[1][126] : 0;
  if (res[1]!=0) res[1][120]=a0;
  a0=arg[1]? arg[1][127] : 0;
  if (res[1]!=0) res[1][121]=a0;
  a0=arg[1]? arg[1][128] : 0;
  if (res[1]!=0) res[1][122]=a0;
  a0=arg[1]? arg[1][129] : 0;
  if (res[1]!=0) res[1][123]=a0;
  a0=arg[1]? arg[1][130] : 0;
  if (res[1]!=0) res[1][124]=a0;
  a0=arg[1]? arg[1][131] : 0;
  if (res[1]!=0) res[1][125]=a0;
  a0=arg[1]? arg[1][120] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][126]=a0;
  a0=arg[1]? arg[1][121] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][127]=a0;
  a0=arg[1]? arg[1][122] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][128]=a0;
  a0=arg[1]? arg[1][123] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][129]=a0;
  a0=arg[1]? arg[1][124] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][130]=a0;
  a0=arg[1]? arg[1][125] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][131]=a0;
  a0=arg[1]? arg[1][138] : 0;
  if (res[1]!=0) res[1][132]=a0;
  a0=arg[1]? arg[1][139] : 0;
  if (res[1]!=0) res[1][133]=a0;
  a0=arg[1]? arg[1][140] : 0;
  if (res[1]!=0) res[1][134]=a0;
  a0=arg[1]? arg[1][141] : 0;
  if (res[1]!=0) res[1][135]=a0;
  a0=arg[1]? arg[1][142] : 0;
  if (res[1]!=0) res[1][136]=a0;
  a0=arg[1]? arg[1][143] : 0;
  if (res[1]!=0) res[1][137]=a0;
  a0=arg[1]? arg[1][132] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][138]=a0;
  a0=arg[1]? arg[1][133] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][139]=a0;
  a0=arg[1]? arg[1][134] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][140]=a0;
  a0=arg[1]? arg[1][135] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][141]=a0;
  a0=arg[1]? arg[1][136] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][142]=a0;
  a0=arg[1]? arg[1][137] : 0;
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][143]=a0;
  a0=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][0]=a0;
  a0=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][1]=a0;
  a0=arg[2]? arg[2][8] : 0;
  if (res[2]!=0) res[2][2]=a0;
  a0=arg[2]? arg[2][9] : 0;
  if (res[2]!=0) res[2][3]=a0;
  a0=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][4]=a0;
  a0=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][5]=a0;
  a0=1.;
  a2=arg[2]? arg[2][0] : 0;
  a2=(a1*a2);
  a2=(a0-a2);
  if (res[2]!=0) res[2][6]=a2;
  a2=arg[2]? arg[2][1] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][7]=a2;
  a2=arg[2]? arg[2][2] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][8]=a2;
  a2=arg[2]? arg[2][3] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][9]=a2;
  a2=arg[2]? arg[2][4] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][10]=a2;
  a2=arg[2]? arg[2][5] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][11]=a2;
  a2=arg[2]? arg[2][18] : 0;
  if (res[2]!=0) res[2][12]=a2;
  a2=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][13]=a2;
  a2=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][14]=a2;
  a2=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][15]=a2;
  a2=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][16]=a2;
  a2=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][17]=a2;
  a2=arg[2]? arg[2][12] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][18]=a2;
  a2=arg[2]? arg[2][13] : 0;
  a2=(a1*a2);
  a2=(a0-a2);
  if (res[2]!=0) res[2][19]=a2;
  a2=arg[2]? arg[2][14] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][20]=a2;
  a2=arg[2]? arg[2][15] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][21]=a2;
  a2=arg[2]? arg[2][16] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][22]=a2;
  a2=arg[2]? arg[2][17] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][23]=a2;
  a2=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][24]=a2;
  a2=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][25]=a2;
  a2=arg[2]? arg[2][32] : 0;
  if (res[2]!=0) res[2][26]=a2;
  a2=arg[2]? arg[2][33] : 0;
  if (res[2]!=0) res[2][27]=a2;
  a2=arg[2]? arg[2][34] : 0;
  if (res[2]!=0) res[2][28]=a2;
  a2=arg[2]? arg[2][35] : 0;
  if (res[2]!=0) res[2][29]=a2;
  a2=arg[2]? arg[2][24] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][30]=a2;
  a2=arg[2]? arg[2][25] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][31]=a2;
  a2=arg[2]? arg[2][26] : 0;
  a2=(a1*a2);
  a2=(a0-a2);
  if (res[2]!=0) res[2][32]=a2;
  a2=arg[2]? arg[2][27] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][33]=a2;
  a2=arg[2]? arg[2][28] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][34]=a2;
  a2=arg[2]? arg[2][29] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][35]=a2;
  a2=arg[2]? arg[2][42] : 0;
  if (res[2]!=0) res[2][36]=a2;
  a2=arg[2]? arg[2][43] : 0;
  if (res[2]!=0) res[2][37]=a2;
  a2=arg[2]? arg[2][44] : 0;
  if (res[2]!=0) res[2][38]=a2;
  a2=arg[2]? arg[2][45] : 0;
  if (res[2]!=0) res[2][39]=a2;
  a2=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][40]=a2;
  a2=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][41]=a2;
  a2=arg[2]? arg[2][36] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][42]=a2;
  a2=arg[2]? arg[2][37] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][43]=a2;
  a2=arg[2]? arg[2][38] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][44]=a2;
  a2=arg[2]? arg[2][39] : 0;
  a2=(a1*a2);
  a2=(a0-a2);
  if (res[2]!=0) res[2][45]=a2;
  a2=arg[2]? arg[2][40] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][46]=a2;
  a2=arg[2]? arg[2][41] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][47]=a2;
  a2=arg[2]? arg[2][54] : 0;
  if (res[2]!=0) res[2][48]=a2;
  a2=arg[2]? arg[2][55] : 0;
  if (res[2]!=0) res[2][49]=a2;
  a2=arg[2]? arg[2][56] : 0;
  if (res[2]!=0) res[2][50]=a2;
  a2=arg[2]? arg[2][57] : 0;
  if (res[2]!=0) res[2][51]=a2;
  a2=arg[2]? arg[2][58] : 0;
  if (res[2]!=0) res[2][52]=a2;
  a2=arg[2]? arg[2][59] : 0;
  if (res[2]!=0) res[2][53]=a2;
  a2=arg[2]? arg[2][48] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][54]=a2;
  a2=arg[2]? arg[2][49] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][55]=a2;
  a2=arg[2]? arg[2][50] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][56]=a2;
  a2=arg[2]? arg[2][51] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][57]=a2;
  a2=arg[2]? arg[2][52] : 0;
  a2=(a1*a2);
  a2=(a0-a2);
  if (res[2]!=0) res[2][58]=a2;
  a2=arg[2]? arg[2][53] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][59]=a2;
  a2=arg[2]? arg[2][66] : 0;
  if (res[2]!=0) res[2][60]=a2;
  a2=arg[2]? arg[2][67] : 0;
  if (res[2]!=0) res[2][61]=a2;
  a2=arg[2]? arg[2][68] : 0;
  if (res[2]!=0) res[2][62]=a2;
  a2=arg[2]? arg[2][69] : 0;
  if (res[2]!=0) res[2][63]=a2;
  a2=arg[2]? arg[2][70] : 0;
  if (res[2]!=0) res[2][64]=a2;
  a2=arg[2]? arg[2][71] : 0;
  if (res[2]!=0) res[2][65]=a2;
  a2=arg[2]? arg[2][60] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][66]=a2;
  a2=arg[2]? arg[2][61] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][67]=a2;
  a2=arg[2]? arg[2][62] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][68]=a2;
  a2=arg[2]? arg[2][63] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][69]=a2;
  a2=arg[2]? arg[2][64] : 0;
  a2=(a1*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][70]=a2;
  a2=arg[2]? arg[2][65] : 0;
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[2]!=0) res[2][71]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_ik_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int robot_ik_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real robot_ik_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_ik_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_ik_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_ik_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_ik_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
