/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_ik_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[81] = {12, 6, 0, 12, 24, 36, 48, 60, 72, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};
static const casadi_int casadi_s5[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s6[175] = {171, 1, 0, 171, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170};

/* robot_ik_expl_ode_hess:(i0[12],i1[12x12],i2[12x6],i3[12],i4[6],i5[0])->(o0[18],o1[171]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=1.0000000000000001e-01;
  a1=arg[3]? arg[3][6] : 0;
  a2=(a0*a1);
  a2=(-a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[3]? arg[3][7] : 0;
  a3=(a0*a2);
  a3=(-a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[3]? arg[3][8] : 0;
  a4=(a0*a3);
  a4=(-a4);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[3]? arg[3][9] : 0;
  a5=(a0*a4);
  a5=(-a5);
  if (res[0]!=0) res[0][3]=a5;
  a5=arg[3]? arg[3][10] : 0;
  a6=(a0*a5);
  a6=(-a6);
  if (res[0]!=0) res[0][4]=a6;
  a6=arg[3]? arg[3][11] : 0;
  a0=(a0*a6);
  a0=(-a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a3;
  if (res[0]!=0) res[0][15]=a4;
  if (res[0]!=0) res[0][16]=a5;
  if (res[0]!=0) res[0][17]=a6;
  a6=0.;
  if (res[1]!=0) res[1][0]=a6;
  if (res[1]!=0) res[1][1]=a6;
  if (res[1]!=0) res[1][2]=a6;
  if (res[1]!=0) res[1][3]=a6;
  if (res[1]!=0) res[1][4]=a6;
  if (res[1]!=0) res[1][5]=a6;
  if (res[1]!=0) res[1][6]=a6;
  if (res[1]!=0) res[1][7]=a6;
  if (res[1]!=0) res[1][8]=a6;
  if (res[1]!=0) res[1][9]=a6;
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a6;
  if (res[1]!=0) res[1][12]=a6;
  if (res[1]!=0) res[1][13]=a6;
  if (res[1]!=0) res[1][14]=a6;
  if (res[1]!=0) res[1][15]=a6;
  if (res[1]!=0) res[1][16]=a6;
  if (res[1]!=0) res[1][17]=a6;
  if (res[1]!=0) res[1][18]=a6;
  if (res[1]!=0) res[1][19]=a6;
  if (res[1]!=0) res[1][20]=a6;
  if (res[1]!=0) res[1][21]=a6;
  if (res[1]!=0) res[1][22]=a6;
  if (res[1]!=0) res[1][23]=a6;
  if (res[1]!=0) res[1][24]=a6;
  if (res[1]!=0) res[1][25]=a6;
  if (res[1]!=0) res[1][26]=a6;
  if (res[1]!=0) res[1][27]=a6;
  if (res[1]!=0) res[1][28]=a6;
  if (res[1]!=0) res[1][29]=a6;
  if (res[1]!=0) res[1][30]=a6;
  if (res[1]!=0) res[1][31]=a6;
  if (res[1]!=0) res[1][32]=a6;
  if (res[1]!=0) res[1][33]=a6;
  if (res[1]!=0) res[1][34]=a6;
  if (res[1]!=0) res[1][35]=a6;
  if (res[1]!=0) res[1][36]=a6;
  if (res[1]!=0) res[1][37]=a6;
  if (res[1]!=0) res[1][38]=a6;
  if (res[1]!=0) res[1][39]=a6;
  if (res[1]!=0) res[1][40]=a6;
  if (res[1]!=0) res[1][41]=a6;
  if (res[1]!=0) res[1][42]=a6;
  if (res[1]!=0) res[1][43]=a6;
  if (res[1]!=0) res[1][44]=a6;
  if (res[1]!=0) res[1][45]=a6;
  if (res[1]!=0) res[1][46]=a6;
  if (res[1]!=0) res[1][47]=a6;
  if (res[1]!=0) res[1][48]=a6;
  if (res[1]!=0) res[1][49]=a6;
  if (res[1]!=0) res[1][50]=a6;
  if (res[1]!=0) res[1][51]=a6;
  if (res[1]!=0) res[1][52]=a6;
  if (res[1]!=0) res[1][53]=a6;
  if (res[1]!=0) res[1][54]=a6;
  if (res[1]!=0) res[1][55]=a6;
  if (res[1]!=0) res[1][56]=a6;
  if (res[1]!=0) res[1][57]=a6;
  if (res[1]!=0) res[1][58]=a6;
  if (res[1]!=0) res[1][59]=a6;
  if (res[1]!=0) res[1][60]=a6;
  if (res[1]!=0) res[1][61]=a6;
  if (res[1]!=0) res[1][62]=a6;
  if (res[1]!=0) res[1][63]=a6;
  if (res[1]!=0) res[1][64]=a6;
  if (res[1]!=0) res[1][65]=a6;
  if (res[1]!=0) res[1][66]=a6;
  if (res[1]!=0) res[1][67]=a6;
  if (res[1]!=0) res[1][68]=a6;
  if (res[1]!=0) res[1][69]=a6;
  if (res[1]!=0) res[1][70]=a6;
  if (res[1]!=0) res[1][71]=a6;
  if (res[1]!=0) res[1][72]=a6;
  if (res[1]!=0) res[1][73]=a6;
  if (res[1]!=0) res[1][74]=a6;
  if (res[1]!=0) res[1][75]=a6;
  if (res[1]!=0) res[1][76]=a6;
  if (res[1]!=0) res[1][77]=a6;
  if (res[1]!=0) res[1][78]=a6;
  if (res[1]!=0) res[1][79]=a6;
  if (res[1]!=0) res[1][80]=a6;
  if (res[1]!=0) res[1][81]=a6;
  if (res[1]!=0) res[1][82]=a6;
  if (res[1]!=0) res[1][83]=a6;
  if (res[1]!=0) res[1][84]=a6;
  if (res[1]!=0) res[1][85]=a6;
  if (res[1]!=0) res[1][86]=a6;
  if (res[1]!=0) res[1][87]=a6;
  if (res[1]!=0) res[1][88]=a6;
  if (res[1]!=0) res[1][89]=a6;
  if (res[1]!=0) res[1][90]=a6;
  if (res[1]!=0) res[1][91]=a6;
  if (res[1]!=0) res[1][92]=a6;
  if (res[1]!=0) res[1][93]=a6;
  if (res[1]!=0) res[1][94]=a6;
  if (res[1]!=0) res[1][95]=a6;
  if (res[1]!=0) res[1][96]=a6;
  if (res[1]!=0) res[1][97]=a6;
  if (res[1]!=0) res[1][98]=a6;
  if (res[1]!=0) res[1][99]=a6;
  if (res[1]!=0) res[1][100]=a6;
  if (res[1]!=0) res[1][101]=a6;
  if (res[1]!=0) res[1][102]=a6;
  if (res[1]!=0) res[1][103]=a6;
  if (res[1]!=0) res[1][104]=a6;
  if (res[1]!=0) res[1][105]=a6;
  if (res[1]!=0) res[1][106]=a6;
  if (res[1]!=0) res[1][107]=a6;
  if (res[1]!=0) res[1][108]=a6;
  if (res[1]!=0) res[1][109]=a6;
  if (res[1]!=0) res[1][110]=a6;
  if (res[1]!=0) res[1][111]=a6;
  if (res[1]!=0) res[1][112]=a6;
  if (res[1]!=0) res[1][113]=a6;
  if (res[1]!=0) res[1][114]=a6;
  if (res[1]!=0) res[1][115]=a6;
  if (res[1]!=0) res[1][116]=a6;
  if (res[1]!=0) res[1][117]=a6;
  if (res[1]!=0) res[1][118]=a6;
  if (res[1]!=0) res[1][119]=a6;
  if (res[1]!=0) res[1][120]=a6;
  if (res[1]!=0) res[1][121]=a6;
  if (res[1]!=0) res[1][122]=a6;
  if (res[1]!=0) res[1][123]=a6;
  if (res[1]!=0) res[1][124]=a6;
  if (res[1]!=0) res[1][125]=a6;
  if (res[1]!=0) res[1][126]=a6;
  if (res[1]!=0) res[1][127]=a6;
  if (res[1]!=0) res[1][128]=a6;
  if (res[1]!=0) res[1][129]=a6;
  if (res[1]!=0) res[1][130]=a6;
  if (res[1]!=0) res[1][131]=a6;
  if (res[1]!=0) res[1][132]=a6;
  if (res[1]!=0) res[1][133]=a6;
  if (res[1]!=0) res[1][134]=a6;
  if (res[1]!=0) res[1][135]=a6;
  if (res[1]!=0) res[1][136]=a6;
  if (res[1]!=0) res[1][137]=a6;
  if (res[1]!=0) res[1][138]=a6;
  if (res[1]!=0) res[1][139]=a6;
  if (res[1]!=0) res[1][140]=a6;
  if (res[1]!=0) res[1][141]=a6;
  if (res[1]!=0) res[1][142]=a6;
  if (res[1]!=0) res[1][143]=a6;
  if (res[1]!=0) res[1][144]=a6;
  if (res[1]!=0) res[1][145]=a6;
  if (res[1]!=0) res[1][146]=a6;
  if (res[1]!=0) res[1][147]=a6;
  if (res[1]!=0) res[1][148]=a6;
  if (res[1]!=0) res[1][149]=a6;
  if (res[1]!=0) res[1][150]=a6;
  if (res[1]!=0) res[1][151]=a6;
  if (res[1]!=0) res[1][152]=a6;
  if (res[1]!=0) res[1][153]=a6;
  if (res[1]!=0) res[1][154]=a6;
  if (res[1]!=0) res[1][155]=a6;
  if (res[1]!=0) res[1][156]=a6;
  if (res[1]!=0) res[1][157]=a6;
  if (res[1]!=0) res[1][158]=a6;
  if (res[1]!=0) res[1][159]=a6;
  if (res[1]!=0) res[1][160]=a6;
  if (res[1]!=0) res[1][161]=a6;
  if (res[1]!=0) res[1][162]=a6;
  if (res[1]!=0) res[1][163]=a6;
  if (res[1]!=0) res[1][164]=a6;
  if (res[1]!=0) res[1][165]=a6;
  if (res[1]!=0) res[1][166]=a6;
  if (res[1]!=0) res[1][167]=a6;
  if (res[1]!=0) res[1][168]=a6;
  if (res[1]!=0) res[1][169]=a6;
  if (res[1]!=0) res[1][170]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_ik_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_ik_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int robot_ik_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real robot_ik_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_ik_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_ik_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_ik_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_ik_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_ik_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
